title: "Almir Lima Jr."
author: ""
description: "Almir Lima Jr."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "blog.md", title: "Projects"}
  - {file: "resume.md", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: E-mail, icon: envelope, url: "mailto:almirlimajr97@icloud.com"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/almirlimajr97/"}
  - {title: GitHub, icon: github, url: "https://github.com/almirlimajr97/"}
  #- {title: BlueSky, icon: bluesky, url: "https://bsky.app/profile/almirlimajr97.bsky.social/"}
  - {title: Lattes, icon: graduation-cap, url: "https://lattes.cnpq.br/8271261828366576/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
